[project]
name = "bixi-mcp"
version = "0.1.0"
description = "Simple MCP server for Bixi web service data access"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.12.0",
    "httpx>=0.25.0",
]
